-- 코드를 입력하세요
SELECT A.WRITER_ID USER_ID, B.NICKNAME NICKNAME, 
CONCAT(B.CITY, ' ' ,B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) 전체주소, 
CONCAT(SUBSTR(B.TLNO, 1, 3), '-', SUBSTR(B.TLNO, 4, 4), '-', SUBSTR(B.TLNO, 8, 4)) 전화번호
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(A.WRITER_ID) >= 3
ORDER BY USER_ID DESC